---

- name: configure php timezone
  lineinfile:
    path: '/etc/opt/rh/rh-php{{ php_fpm_php_version }}/php.ini'
    regexp: '^date.timezone( )?='
    line: 'date.timezone = Europe/Zurich'
  notify: php_fpm restart php-fpm
