---

- name: install neccesary packages
  package:
    name: '{{ item }}'
    state: present
  register: php_fpm_register_packages_installed
  until: php_fpm_register_packages_installed is success
  retries: 3
  delay: 2
  when: ansible_distribution == 'CentOS'
  with_items:
    - centos-release-scl
    - rh-php72-php-fpm

- name: start and enable php-fpm service
  service:
    name: rh-php72-php-fpm.service
    state: started
    enabled: true
